name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  precommit-check:
    runs-on: ubuntu-latest

    permissions:
        contents: read
        pull-requests: write

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python (for pre-commit)
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

       # 4️⃣ Ensure Tools are installed (from your shell script)
      - name: Ensure Tools Installed
        run: bash scripts/install_tools.sh

      - name: Run Pre-Commit Hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      # 5️⃣ Codeql for Trivy IaC
      - name: codeql Trivy IaC
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: trivy-iac.sarif


      # 7️⃣ Codeql for Checkov
      - name: codeql Checkov
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: checkov.sarif
